server:
  port: 8900
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.132:8848
        password: nacos
        username: nacos
    gateway:
      discovery:
        locator:
          enabled: true #开启服务发现
          lower-case-service-id: true
      routes:
        - id: baidu
          predicates:   #断言
            - Path=/baidu  #匹配规则
          filters:
            - StripPrefix=1
          uri: http://www.baidu.com  #跳转地址：http://192.168.211.1:8900/baidu转到百度
        - id: bilibili
          predicates:
            - Path=/bilibili
          filters:
            - StripPrefix=1
          uri: https://space.bilibili.com/215563138
        - id: test-server1
          predicates:
            #- Path=/request-api/request/**
            #gateway跳转路径：http://192.168.211.1:8900/test-server/test/request/getUser?id=911592303011950590
            - Path=/test1/**
          filters:
            - StripPrefix=1
            - Log=true
            - Time=true
            - DecryptRequestBodyFilter=true
          uri: lb://test-server
          order: 1
          #uri: http://192.168.211.1:8081


