spring:
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    username: admin
    password: 123
    #开启发布确认
    publisher-confirm-type: correlated
    # 消息回退
    publisher-returns: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
